#! /bin/sh

# The default LUA_PATH including the path of luarocks-installed modules
eval `luarocks path`

# Augment LUA_PATH with csagent module path
export LUA_PATH="/usr/share/csagent/?.lua;$LUA_PATH"
export LUA_CPATH="/usr/lib/lua/?.so;$LUA_CPATH"

gid="`uci get csagent.@main[0].gid`"
roles="`uci get csagent.@main[0].roles`"
agentcontroller_jsonrpc_url="`uci get csagent.@main[0].agentcontroller_jsonrpc_url`"

exec lua /usr/share/csagent/csagent.lua -c "$agentcontroller_jsonrpc_url" -r "$roles" $gid
