#! /bin/sh

# The default LUA_PATH including the path of luarocks-installed modules
eval `luarocks path`

# Augment LUA_PATH with csagent module path
export LUA_PATH="/usr/share/csagent/?.lua;$LUA_PATH"
export LUA_CPATH="/usr/lib/lua/?.so;$LUA_CPATH"

echo $@
lua /usr/share/csagent/csagent.lua $@
